// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Greeting$Whatever = require("./greeting.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Greeting$Whatever.make("Parcel", /* array */[])), "app");

/*  Not a pure module */
